language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer update

script:
    - ./vendor/bin/phpcs --standard=phpcs.xml src
    - ./vendor/bin/phpunit -c .
